name: Ensuring
on:
  push:
    branches:
      - 'samples/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Recreate samples
        run: |
          ./bin/utils/ensure-up-to-date
          git config user.email "${{ secrets.MY_EMAIL }}"
          git config user.name "Jim Schubert"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add samples/
          git commit -m "[samples] Regenerated"
          git push origin ${GITHUB_REF#refs/heads/}
